### ISSUE TITLE
Product Launch Date Mismatched

### ISSUE THREAD

**Issue by Anandkalyan2190** [hunted-space/hunted-space-blog#3]
Hello, we have plans to launch our new product on Aug 4th. We have set the date in product hunt but in hunted. space the launch date is showing wrongly. Our product name is Build Chatbot. 
![image](https://github.com/hunted-space/hunted-space-blog/assets/141264042/bd16708c-db94-4ed7-ac7e-3c8c508a947c)

**Comment by danmindru** [comment]
Hey! Sorry for the late reply.
I see it was updated in the meantime.
It goes a bit quicker if you write to the https://twitter.com/hunteddotspace twitter!
For the next launch :-)
